### ISSUE TITLE
Cannot import library to use

### ISSUE THREAD

**Issue by SarahEhabMostafa** [jhw-dev/CircleLoadingView#1]
I've added the library dependency (`compile 'com.github.jhw-dev:CircleLoadingView:1.3'`) to my build.gradle and I keep on getting a "**Failed to resolve: com.github.jhw-dev:CircleLoadingView:1.3**" error. My repositories is as follows: 

```
repositories {
        mavenCentral()
        jcenter()
        maven {
            url "https://jitpack.io"
        }
}
```

Please help! This is very frustrating!

**Comment by zerob13** [comment]
change 
compile 'com.github.jhw-dev:CircleLoadingView:1.3'
to
compile 'com.github.jhw-dev:CircleLoadingView:v1.3'

Please read the README carefully.
Thank you for your feedback:)
